/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ufjf.dcc025.encorecrossover.eengine;

import br.ufjf.dcc025.encorecrossover.edata.EData;
import br.ufjf.dcc025.encorecrossover.euser.EPlayer;
import br.ufjf.dcc025.encorecrossover.euser.EUser;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author b4bru
 */
public class EScreen extends javax.swing.JFrame {

    /**
     * Creates new form EScreen
     */
    public EScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        layeredPane = new javax.swing.JLayeredPane();
        userPane = new javax.swing.JPanel();
        userTabbedPane = new javax.swing.JTabbedPane();
        userCharPanel = new javax.swing.JPanel();
        favCharSplitPane = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        favCharList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        selectedCharTextArea = new javax.swing.JTextArea();
        charListToolBar = new javax.swing.JToolBar();
        newGameButton = new javax.swing.JButton();
        removeCharacterButton = new javax.swing.JButton();
        userHistoryPanel = new javax.swing.JPanel();
        historyToolBar = new javax.swing.JToolBar();
        historyConfirmButton = new javax.swing.JButton();
        historyRemoveButton = new javax.swing.JButton();
        historySplitPane = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        historyList = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        historyTextArea = new javax.swing.JTextArea();
        loginPane = new javax.swing.JPanel();
        loginPaneLabel = new javax.swing.JLabel();
        loginInnerPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        gamePane = new javax.swing.JPanel();
        inGameActionPanel = new javax.swing.JPanel();
        actionLabel = new javax.swing.JLabel();
        actionComboBox = new javax.swing.JComboBox<>();
        targetLabel = new javax.swing.JLabel();
        targetComboBox = new javax.swing.JComboBox<>();
        executeButton = new javax.swing.JButton();
        inGameStatsPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        inGameCharTextArea1 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        selectedActionTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        inGameCharTextArea2 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        turnSummaryTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        userMenu = new javax.swing.JMenu();
        editUserMenu = new javax.swing.JMenu();
        editNameMenuItem = new javax.swing.JMenuItem();
        editPasswordMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        charMenu = new javax.swing.JMenu();
        listCharMenuItem = new javax.swing.JMenuItem();
        createCharMenuItem = new javax.swing.JMenuItem();
        skillsMenu = new javax.swing.JMenu();
        listSkillsMenuItem = new javax.swing.JMenuItem();
        createSkillMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jButton3.setText("jButton3");

        jButton6.setText("jButton6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Encore Crossover");
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(640, 480));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setSize(new java.awt.Dimension(640, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        layeredPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Made by BeeHive", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Comic Sans MS", 0, 14))); // NOI18N
        layeredPane.setPreferredSize(new java.awt.Dimension(870, 440));
        layeredPane.setLayout(new javax.swing.OverlayLayout(layeredPane));

        userPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "User", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        userPane.setForeground(new java.awt.Color(102, 102, 102));
        userPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                userPaneComponentShown(evt);
            }
        });
        userPane.setLayout(new javax.swing.BoxLayout(userPane, javax.swing.BoxLayout.LINE_AXIS));

        userTabbedPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userCharPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userCharPanel.setLayout(new java.awt.BorderLayout());

        favCharSplitPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Favorite Characters"));
        favCharSplitPane.setDividerLocation(150);

        favCharList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Character 1", "Character 2", "Character 3", "Character 4", "Character 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        favCharList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(favCharList);

        favCharSplitPane.setLeftComponent(jScrollPane1);

        selectedCharTextArea.setEditable(false);
        selectedCharTextArea.setColumns(20);
        selectedCharTextArea.setLineWrap(true);
        selectedCharTextArea.setRows(5);
        selectedCharTextArea.setText("Name\nSkill 1\nSkill 2\nSkill 3\n...\n");
        jScrollPane2.setViewportView(selectedCharTextArea);

        favCharSplitPane.setRightComponent(jScrollPane2);

        userCharPanel.add(favCharSplitPane, java.awt.BorderLayout.CENTER);

        charListToolBar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Options"));
        charListToolBar.setRollover(true);

        newGameButton.setText("New Game");
        charListToolBar.add(newGameButton);

        removeCharacterButton.setText("Remove Character");
        removeCharacterButton.setFocusable(false);
        removeCharacterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeCharacterButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        charListToolBar.add(removeCharacterButton);

        userCharPanel.add(charListToolBar, java.awt.BorderLayout.PAGE_END);

        userTabbedPane.addTab("New Game", userCharPanel);

        userHistoryPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userHistoryPanel.setLayout(new java.awt.BorderLayout());

        historyToolBar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Options"));
        historyToolBar.setRollover(true);

        historyConfirmButton.setText("Confirm");
        historyConfirmButton.setFocusable(false);
        historyConfirmButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        historyConfirmButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        historyToolBar.add(historyConfirmButton);

        historyRemoveButton.setText("Remove");
        historyRemoveButton.setFocusable(false);
        historyRemoveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        historyRemoveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        historyToolBar.add(historyRemoveButton);

        userHistoryPanel.add(historyToolBar, java.awt.BorderLayout.PAGE_END);

        historySplitPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Entries"));
        historySplitPane.setDividerLocation(150);

        historyList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "History 1", "History 2", "History 3", "History 4", "History 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        historyList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(historyList);

        historySplitPane.setLeftComponent(jScrollPane3);

        historyTextArea.setEditable(false);
        historyTextArea.setColumns(20);
        historyTextArea.setLineWrap(true);
        historyTextArea.setRows(5);
        historyTextArea.setText("Selected Character's Information\n");
        jScrollPane4.setViewportView(historyTextArea);

        historySplitPane.setRightComponent(jScrollPane4);

        userHistoryPanel.add(historySplitPane, java.awt.BorderLayout.CENTER);

        userTabbedPane.addTab("History", userHistoryPanel);

        userPane.add(userTabbedPane);

        layeredPane.add(userPane);

        loginPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Login", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        loginPane.setLayout(new java.awt.BorderLayout());

        loginPaneLabel.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        loginPaneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginPaneLabel.setText("Encore Crossover");
        loginPane.add(loginPaneLabel, java.awt.BorderLayout.CENTER);

        loginInnerPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginInnerPanel.setLayout(new javax.swing.BoxLayout(loginInnerPanel, javax.swing.BoxLayout.LINE_AXIS));

        usernameLabel.setText("Username:");
        loginInnerPanel.add(usernameLabel);

        usernameField.setText("Username");
        usernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFieldFocusGained(evt);
            }
        });
        loginInnerPanel.add(usernameField);

        passwordLabel.setText("Password:");
        loginInnerPanel.add(passwordLabel);

        passwordField.setText("Password");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });
        loginInnerPanel.add(passwordField);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginInnerPanel.add(loginButton);

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        loginInnerPanel.add(createButton);

        loginPane.add(loginInnerPanel, java.awt.BorderLayout.PAGE_END);

        loginPane.setVisible(true);
        userPane.setVisible(false);
        gamePane.setVisible(false);

        layeredPane.add(loginPane);

        gamePane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Game", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        gamePane.setLayout(new java.awt.BorderLayout());

        inGameActionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Action"));
        inGameActionPanel.setLayout(new javax.swing.BoxLayout(inGameActionPanel, javax.swing.BoxLayout.LINE_AXIS));

        actionLabel.setText("Action:");
        inGameActionPanel.add(actionLabel);

        actionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        inGameActionPanel.add(actionComboBox);

        targetLabel.setText("Target:");
        inGameActionPanel.add(targetLabel);

        targetComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        inGameActionPanel.add(targetComboBox);

        executeButton.setText("Execute");
        inGameActionPanel.add(executeButton);

        gamePane.add(inGameActionPanel, java.awt.BorderLayout.PAGE_END);

        inGameStatsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Current Status"));
        inGameStatsPanel.setLayout(new javax.swing.BoxLayout(inGameStatsPanel, javax.swing.BoxLayout.LINE_AXIS));

        inGameCharTextArea1.setEditable(false);
        inGameCharTextArea1.setColumns(20);
        inGameCharTextArea1.setLineWrap(true);
        inGameCharTextArea1.setRows(5);
        inGameCharTextArea1.setText("Character 1\nHP: xx/xx\nEffects: effectx, effecty, effectz");
        jScrollPane5.setViewportView(inGameCharTextArea1);

        inGameStatsPanel.add(jScrollPane5);

        selectedActionTextArea.setEditable(false);
        selectedActionTextArea.setColumns(20);
        selectedActionTextArea.setLineWrap(true);
        selectedActionTextArea.setRows(5);
        selectedActionTextArea.setText("Selected Action's Description\n");
        jScrollPane8.setViewportView(selectedActionTextArea);

        inGameStatsPanel.add(jScrollPane8);

        inGameCharTextArea2.setEditable(false);
        inGameCharTextArea2.setColumns(20);
        inGameCharTextArea2.setLineWrap(true);
        inGameCharTextArea2.setRows(5);
        inGameCharTextArea2.setText("Character 2\nHP: xx/xx\nEffects: effectx, effecty, effectz");
        jScrollPane6.setViewportView(inGameCharTextArea2);

        inGameStatsPanel.add(jScrollPane6);

        gamePane.add(inGameStatsPanel, java.awt.BorderLayout.CENTER);

        turnSummaryTextArea.setEditable(false);
        turnSummaryTextArea.setColumns(20);
        turnSummaryTextArea.setLineWrap(true);
        turnSummaryTextArea.setRows(5);
        turnSummaryTextArea.setText("Fulano takes x damage from effectx\nFulano uses Skill1 on Ciclano\nCiclano takes x damage\nCiclano takes x damage from effectx\nCiclano uses Skill 2 on Ciclano\nCiclano heals x HP");
        jScrollPane7.setViewportView(turnSummaryTextArea);

        gamePane.add(jScrollPane7, java.awt.BorderLayout.PAGE_START);

        layeredPane.add(gamePane);

        userMenu.setText("User");

        editUserMenu.setText("Edit");

        editNameMenuItem.setText("Name");
        editUserMenu.add(editNameMenuItem);

        editPasswordMenuItem.setText("Password");
        editUserMenu.add(editPasswordMenuItem);

        userMenu.add(editUserMenu);

        exitMenuItem.setText("Exit");
        userMenu.add(exitMenuItem);

        jMenuBar1.add(userMenu);

        charMenu.setText("Characters");

        listCharMenuItem.setText("List");
        listCharMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCharMenuItemActionPerformed(evt);
            }
        });
        charMenu.add(listCharMenuItem);

        createCharMenuItem.setText("Create");
        charMenu.add(createCharMenuItem);

        jMenuBar1.add(charMenu);

        skillsMenu.setText("Skills");

        listSkillsMenuItem.setText("List");
        skillsMenu.add(listSkillsMenuItem);

        createSkillMenuItem.setText("Create");
        skillsMenu.add(createSkillMenuItem);

        jMenuBar1.add(skillsMenu);

        helpMenu.setText("Help");

        helpMenuItem.setText("Help");
        helpMenu.add(helpMenuItem);

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(layeredPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listCharMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCharMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listCharMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        user = EUser.login(usernameField.getText(), passwordField.getText());
        if(user != null){
            JOptionPane.showMessageDialog(loginPane, "Login successful.", "Login", 1);
            loginPane.setVisible(false);
            layeredPane.setLayer(loginPane, layeredPane.lowestLayer());
            userPane.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(loginPane, "Login failed.", "Login", 0);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void usernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFieldFocusGained
        // TODO add your handling code here:
        usernameField.selectAll();
    }//GEN-LAST:event_usernameFieldFocusGained

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFieldFocusLost
        // TODO add your handling code here:
        passwordField.selectAll();
    }//GEN-LAST:event_passwordFieldFocusLost

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        user = EPlayer.create(usernameField.getText(), passwordField.getText());
        if(user != null){
            JOptionPane.showMessageDialog(loginPane, "New user created succesfully.", "Login", 1);
            loginPane.setVisible(false);
            layeredPane.setLayer(loginPane, layeredPane.lowestLayer());
            userPane.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(loginPane, "Username in use.", "Login Failed", 0);
    }//GEN-LAST:event_createButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        EData.exportData();
    }//GEN-LAST:event_formWindowClosing

    private void userPaneComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_userPaneComponentShown
        // TODO add your handling code here:
        List<String> list = new ArrayList<>();
        list.addAll(user.getFavList());
        String charList []= new String[list.size()];
        for(int i = 0; i < list.size(); i++){
            charList[i] = list.get(i);
        }
        favCharList.setListData(charList);
    }//GEN-LAST:event_userPaneComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EScreen().setVisible(true);
            }
        });
    }
    //BeeHive
    private EUser user;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JComboBox<String> actionComboBox;
    private javax.swing.JLabel actionLabel;
    private javax.swing.JToolBar charListToolBar;
    private javax.swing.JMenu charMenu;
    private javax.swing.JButton createButton;
    private javax.swing.JMenuItem createCharMenuItem;
    private javax.swing.JMenuItem createSkillMenuItem;
    private javax.swing.JMenuItem editNameMenuItem;
    private javax.swing.JMenuItem editPasswordMenuItem;
    private javax.swing.JMenu editUserMenu;
    private javax.swing.JButton executeButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JList<String> favCharList;
    private javax.swing.JSplitPane favCharSplitPane;
    private javax.swing.JPanel gamePane;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem helpMenuItem;
    private javax.swing.JButton historyConfirmButton;
    private javax.swing.JList<String> historyList;
    private javax.swing.JButton historyRemoveButton;
    private javax.swing.JSplitPane historySplitPane;
    private javax.swing.JTextArea historyTextArea;
    private javax.swing.JToolBar historyToolBar;
    private javax.swing.JPanel inGameActionPanel;
    private javax.swing.JTextArea inGameCharTextArea1;
    private javax.swing.JTextArea inGameCharTextArea2;
    private javax.swing.JPanel inGameStatsPanel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JMenuItem listCharMenuItem;
    private javax.swing.JMenuItem listSkillsMenuItem;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginInnerPanel;
    private javax.swing.JPanel loginPane;
    private javax.swing.JLabel loginPaneLabel;
    private javax.swing.JButton newGameButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton removeCharacterButton;
    private javax.swing.JTextArea selectedActionTextArea;
    private javax.swing.JTextArea selectedCharTextArea;
    private javax.swing.JMenu skillsMenu;
    private javax.swing.JComboBox<String> targetComboBox;
    private javax.swing.JLabel targetLabel;
    private javax.swing.JTextArea turnSummaryTextArea;
    private javax.swing.JPanel userCharPanel;
    private javax.swing.JPanel userHistoryPanel;
    private javax.swing.JMenu userMenu;
    private javax.swing.JPanel userPane;
    private javax.swing.JTabbedPane userTabbedPane;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
